support for overlayfs

diff --git a/2insert.diff b/2insert.diff
--- a/2insert.diff
+++ b/2insert.diff
@@ -1,8 +1,8 @@
---- init.r	2022-06-14 12:49:05.625052000 +1000
-+++ init	2022-06-14 12:49:50.239055562 +1000
-@@ -90,6 +90,15 @@
- #Filesystem to be fsck
- FSCKLIST="ext2|ext3|ext4|vfat|msdos|exfat"
+--- init.rem	2022-07-24 03:10:26.484071575 +1000
++++ init.ins	2022-07-24 03:16:52.188097607 +1000
+@@ -93,6 +93,15 @@
+ # Layered file system to use
+ UNIONFS='aufs'
  
 +# ?drv_...sfs files to load below puppy_...sfs
 +#APPEND_DRVS="q r s t u v w x"
@@ -16,7 +16,7 @@
  #=============================================================
  #                        FUNCTIONS
  #=============================================================
-@@ -251,6 +260,155 @@
+@@ -256,6 +265,163 @@
   fi
  }
  
@@ -63,7 +63,7 @@
 +    esac
 +  fi
 +  if [ "$PART" ];then
-+    ensure_mounted "$PART" "/mnt/${2}drv" #sets ONE_MP an ONE_FS
++    ensure_mounted "$PART" "/mnt/${2}drv" #sets ONE_MP and ONE_FS
 +    if [ "$ONE_MP" ];then
 +      SPEC_MP="$ONE_MP"
 +      SPEC_FS="$ONE_FS"
@@ -99,6 +99,19 @@
 +  fi
 +}
 +
++do_one_sfs_spec() {
++  # $1 = sfs-spec
++  # $2 = drvId  e.g. 'a' or 'f'
++  # $3 = disposition 'a' or 'p' for 'append|prepend'
++    interpret_spec "$1" "$2"
++    [ "$SPEC_PART" ] || return 11
++    find_drv_file "$SPEC_MP" "$SPEC_REL_FN"
++    [ "$ONE_FN" ] || return 13
++    SPEC_REL_FN="$ONE_FN"
++    setup_onepupdrv "${2}" "${3}"
++    return $?
++}
++
 +process_one_sfs() {
 +  # $1 = drvId  e.g. 'a' or 'f'
 +  # $2 = disposition 'a' or 'p' for 'append|prepend'
@@ -106,8 +119,8 @@
 +  # sets $SPEC_REL_FN if the original was a symbolic link
 +  echo "process_one_sfsIN 1=$1 2=$2"
 +  [ "$1" ] || return 1
-+  local ONE_SFS_SPEC=''
-+  local ROOTFS_SPEC=''
++  local ONE_SFS_SPEC ROOTFS_SPEC SPEC_VAR
++  ONE_SFS_SPEC=''; ROOTFS_SPEC=''
 +  # set default filename
 +  if [ "$1" = 'p' ];then
 +    ONE_DEF_FN="$DISTRO_PUPPYSFS"
@@ -133,7 +146,8 @@
 +      esac
 +    fi
 +  elif [ "$1" != 'k' ];then
-+    eval ONE_SFS_SPEC="\$${1}drv"
++    SPEC_VAR="${1}drv" # defined in boot parameter
++    eval ONE_SFS_SPEC="\$$SPEC_VAR"
 +  fi
 +  if [ "$ONE_SFS_SPEC" = "" ];then
 +    if [ "$ROOTFS_SPEC" ];then
@@ -146,17 +160,11 @@
 +    fi
 +  fi
 +  if [ "$ONE_SFS_SPEC" ];then
-+    interpret_spec "$ONE_SFS_SPEC" "$1"
-+    [ "$SPEC_PART" ] || return 3
-+    find_drv_file "$SPEC_MP" "$SPEC_REL_FN"
-+    if [ "$ONE_FN" = "" ];then
-+      echo "${SPEC_REL_FN##*/}, file not found"
++    do_one_sfs_spec "$ONE_SFS_SPEC" "$1" "$2"
++    if [ $? -ne 0 ];then
++      echo "${ONE_SFS_SPEC##*/}, file not found"
 +      return 3
 +    fi
-+    SPEC_REL_FN="$ONE_FN"
-+    setup_onepupdrv "${1}" "${2}"
-+    STATUS=$?
-+    [ $STATUS -eq 0 ] || return $STATUS
 +    local PLACE="${SPEC_PART},${SPEC_FS},${SPEC_REL_FN}"
 +    if [ "$1" = 'p' ];then
 +      PUPSFS="$PLACE"
@@ -172,10 +180,16 @@
  setup_onepupdrv() {
  # "$1" - sfs spec - ex: sdb2,ext4,/pup/mydrv-1.2.3.sfs
  # "$2" - suffix for "pup_" branch directory - ex: a
-@@ -741,6 +899,22 @@
+@@ -782,6 +948,26 @@
  
  [ "$PDEBUG" ] && echo "1: PDRV=$PDRV P_BP_ID=$P_BP_ID P_BP_FN=$P_BP_FN"
  
++#completely sortout info on the stack structure
++#create appropriate stack only at the end, either aufs or overlayfs
++RO_DIR_LIST=''			# ':' separated list of sfs MP's in stack order
++RW_DIR=''				# directory to go at top of stack, usually contains SAVE data
++RO_DIR=''				# MP of "pup_ro1" for odd pupmode, empty otherwise
++
 +get_part_info
 +grep -v '^sr' /tmp/ALLDRVS0 > /tmp/ATADRIVES0
 +ATAOPTICALDRIVES="$(grep '^sr' /tmp/ALLDRVS0 | tr '\n' ' ')"
@@ -186,8 +200,6 @@
 +
 +mount -t tmpfs tmpfs /mnt/tmpfs
 +[ -d "/mnt/tmpfs/pup_rw" ] || mkdir /mnt/tmpfs/pup_rw
-+mount -t aufs -o udba=reval,diropq=w,br=/mnt/tmpfs/pup_rw=rw,xino=/mnt/tmpfs/.aufs.xino unionfs /pup_new 
-+[ $? -eq 0 ] || fatal_error "${L_ERROR_FAILED_AUFS_STACK}"
 +
 +NEWUNIONRECORD=""
 +COPY2RAM=""
@@ -195,7 +207,7 @@
  #"pdrv" is not specified on CD, so look for CD file system
  if [ "$PMEDIA" = "cd" ];then
   wait_for_blkid 'iso9660' 'fs'
-@@ -752,6 +926,11 @@
+@@ -793,6 +979,11 @@
  fi
  
  #establish PDRV
@@ -207,7 +219,7 @@
    wait_for_dev
    USBDRVS="$(find /sys/block -maxdepth 1 -name 'sd*' -o -name 'sr*' | xargs -n 1 readlink 2>/dev/null | grep '/usb[0-9]' | rev | cut -f 1 -d '/' | rev | tr '\n' '|')"
    [ "$PDEBUG" ] && echo "2: USBDRVS=$USBDRVS -> ${USBDRVS%|}"
-@@ -762,8 +941,50 @@
+@@ -803,8 +994,50 @@
    fi
   fi
  fi
@@ -258,3 +270,69 @@
  decode_other_ids
  if [ "$P_PART" ];then
   BOOTDRV="$(echo -n "$P_PART" | grep -o -f /tmp/ALLDRVS0)" #110205 ex: sda1 becomes sda.
+@@ -1094,6 +1327,65 @@
+  ;;
+ esac
+ 
++#create appropriate stack
++echo ""
++if [ "$UNIONFS" = 'overlay' ];then
++  if [ "$RW_DIR" = '/mnt/tmpfs/pup_rw' ];then
++    WK_DIR='/mnt/tmpfs/pup_work'
++  else
++    WK_DIR="${RW_DIR}/work"
++    RW_DIR="${RW_DIR}/upper"
++  fi
++  [ -d "$RW_DIR" ] || mkdir "$RW_DIR"
++  [ -d "$WK_DIR" ] || mkdir "$WK_DIR"
++  [ -e /pup_rw ] && rm -rf /pup_rw
++  ln -sfv "$RW_DIR" /pup_rw
++  [ -e /pup_work ] && rm -rf /pup_work
++  ln -sfv "$WK_DIR" /pup_work
++  [ "$RO_DIR" ] && RO_DIR_LIST="${RO_DIR}:{RO_DIR_LIST}"
++#append extra sfs files
++  if [ "$PUPSAVE" -a -s /pup_rw/etc/rc.d/BOOTCONFIG ];then
++    SAVE_SPEC="${PUPSAVE%/*}"
++    SFS_SPEC="${PUPSFS%/*}"
++    X_PART="${SAVE_SPEC%%,*}"
++    X_DIR="${SAVE_SPEC##*,}"
++    LOADMSG="extra"
++    EXTRASFSLIST=''
++    . /pup_rw/etc/rc.d/BOOTCONFIG
++    for X_SFS in $EXTRASFSLIST;do
++      NUM=$(losetup -f); NUM=${NUM#/dev/loop}
++      if [ "$SAVE_SPEC" = "$SFS_SPEC" ];then
++        X_LIST="${X_PART}:${X_DIR}/${X_SFS} $X_PART:/${X_SFS}"
++      else
++        X_LIST="${X_PART}:${X_DIR}/${X_SFS} $X_PART:/${X_SFS} :${X_SFS}"
++      fi
++      for X_SPEC in $X_LIST;do
++        do_one_sfs_spec "$X_SPEC" "ro${NUM}"
++        STATUS=$?
++        [ $STATUS -eq 0 ] && break
++      done
++      if [ $STATUS -eq 0 ];then
++        echo "Using ${SPEC_MP}${SPEC_REL_FN} as an extra sfs file, pup_ro${NUM}."
++      else
++        echo "${X_SFS}, file not found"
++      fi
++    done
++  fi
++  echo "mount -t overlay -o lowerdir=${RO_DIR_LIST},upperdir=/pup_rw,workdir=/pup_work,xino=on unionfs /pup_new"
++  mount -t overlay -o lowerdir=${RO_DIR_LIST},upperdir=/pup_rw,workdir=/pup_work,xino=on unionfs /pup_new
++else
++  if [ ! -L /pup_rw ];then
++    [ -e /pup_rw ] && rm -rf /pup_rw
++    ln -sfv "$RW_DIR" /pup_rw
++  fi
++  RO_DIR_LIST="${RO_DIR_LIST//:/=rr:}=rr"
++  [ "$RO_DIR" ] && RO_DIR_LIST="${RO_DIR}=ro+wh:${RO_DIR_LIST}"
++  echo "mount -t aufs -o udba=reval,diropq=w,br=/pup_rw=rw:${RO_DIR_LIST},xino=/mnt/tmpfs/.aufs.xino unionfs /pup_new"
++  mount -t aufs -o udba=reval,diropq=w,br=/pup_rw=rw:${RO_DIR_LIST},xino=/mnt/tmpfs/.aufs.xino unionfs /pup_new
++fi
++[ $? -eq 0 ] || fatal_error "$(printf "${L_ERROR_FAILED_STACK}" $UNIONFS)"
++echo ""
++
+ umount_unneeded
+ 
+ echo -n $(($TOTAL_SIZEK_SFS_RAM - 5)) > /tmp/sfs_ram_sizek
diff --git a/3update.diff b/3update.diff
--- a/3update.diff
+++ b/3update.diff
@@ -1,6 +1,15 @@
---- init.orig	2022-06-14 12:57:00.671084613 +1000
-+++ init	2022-06-14 12:58:28.272090526 +1000
-@@ -179,9 +179,13 @@
+--- init.ins	2022-07-24 03:16:52.188097607 +1000
++++ init+drv+overlay	2022-07-23 17:39:49.630004000 +1000
+@@ -45,7 +45,7 @@
+ L_SWITCH_ROOT="Performing a 'switch_root' to the %s filesystem..." #printf
+ L_FOLDER_MARKED_BAD="Folder %s marked bad." #printf
+ L_0_NONE="0  none"
+-L_ERROR_FAILED_AUFS_STACK='Failed to create empty aufs stack'
++L_ERROR_FAILED_STACK="Failed to create %s stack." #printf
+ L_ADDING_MODULE="Adding module %s" #printf
+ L_NO_DISTRO_SPECS="No DISTRO_SPECS file found, assuming that personal storage is empty."
+ L_DEBUG_SAVE="To save debug info to a partition, type 'debugsave'"
+@@ -182,9 +182,13 @@
    sleep 1
    echo -en "\\033[1;33m.\\033[0;39m" >/dev/console #yellow dot
   done
@@ -16,7 +25,20 @@
    if [ "$PART" ];then
     check_status 0
    else
-@@ -410,29 +414,14 @@
+@@ -254,10 +258,8 @@
+   if [ "$ONE_MP" != "$SAVE_MP" ];then
+    #ensure SAVEPART is mounted on /mnt/dev_save
+    [ -d "$SAVE_MP" ] || mkdir -p $SAVE_MP
+-   OPT="move"
+-   [ "$UNIONFS" = 'overlay' ] && OPT="bind"
+-   echo "mount -o $OPT $ONE_MP $SAVE_MP" #debug
+-   mount -o $OPT $ONE_MP $SAVE_MP
++   echo "mount -o move $ONE_MP $SAVE_MP" #debug
++   mount -o move $ONE_MP $SAVE_MP
+   fi
+   SAVE_FS="$ONE_FS"
+  else
+@@ -423,29 +429,14 @@
  }
  
  setup_onepupdrv() {
@@ -53,7 +75,7 @@
   if ! [ -s "$ONE_FN" ] ; then
     return 3 #sfs not Ok - empty file
   fi
-@@ -445,6 +434,9 @@
+@@ -458,6 +449,9 @@
     COPY2RAM="no"
   fi
   #-
@@ -63,7 +85,7 @@
   if [ "$COPY2RAM" = "" ];then
    COPY2RAM="no"
    #if there's heaps of ram, copy puppy.sfs to a tmpfs...
-@@ -461,22 +453,22 @@
+@@ -474,22 +468,22 @@
    SIZEZK=$(du -k $ONE_FN | cut -f 1)
    TFREEK=$(df | grep -m1 ' /mnt/tmpfs' | tr -s ' ' | cut -f 4 -d ' ')
    if [ $TFREEK -gt $SIZEZK ];then
@@ -91,7 +113,86 @@
   fi
   SFS_MP="/pup_${ONE_SFX}"
   [ "$ONE_SFX" = "p" ] && SFS_MP="/pup_ro2"
-@@ -700,7 +692,7 @@
+@@ -501,31 +495,12 @@
+  if ! [ "$ONE_LAYER" ] ; then
+    return 4 #sfs mount failed
+  fi
+- if [ -n "$punionfs" ]; then
+-  UNIONFS="$punionfs"
+- elif [ -f $SFS_MP/etc/rc.d/PUPSTATE ]; then
+-  . $SFS_MP/etc/rc.d/PUPSTATE
+-  [ -n "$PUNIONFS" ] && UNIONFS="$PUNIONFS"
+- fi
+- if [ "$UNIONFS" = 'overlay' ]; then
+-  remount_overlay -e "s~lowerdir=([^,]+)~lowerdir=${SFS_MP}:\1~" -e "s~lowerdir=,~lowerdir=${SFS_MP},~"
+-  [ $? -eq 0 ] || return 5
++ if [ "$ONE_SFX" = "p" ];then
++   RO_DIR_LIST="$SFS_MP"
++ elif [ "$ONE_PREP" ];then
++   RO_DIR_LIST="${SFS_MP}:${RO_DIR_LIST}"
+  else
+-  mountpoint -q /pup_new
+-  if [ $? -ne 0 ];then
+-   echo "mount -t aufs -o udba=reval,diropq=w,br=/mnt/tmpfs/pup_rw=rw,xino=/mnt/tmpfs/.aufs.xino unionfs /pup_new" #debug
+-   mount -t aufs -o udba=reval,diropq=w,br=/mnt/tmpfs/pup_rw=rw,xino=/mnt/tmpfs/.aufs.xino unionfs /pup_new
+-   [ $? -eq 0 ] || fatal_error "${L_ERROR_FAILED_AUFS_STACK}"
+-  fi
+-  if [ "$ONE_PREP" ];then
+-   echo "mount -o remount,add:1:$ONE_LAYER /pup_new" #debug
+-   mount -o remount,add:1:$ONE_LAYER /pup_new
+-   [ $? -eq 0 ] || return 5
+-  else
+-   echo "mount -o remount,append:$ONE_LAYER /pup_new" #debug
+-   mount -o remount,append:$ONE_LAYER /pup_new
+-   [ $? -eq 0 ] || return 5
+-  fi
++   RO_DIR_LIST="${RO_DIR_LIST}:${SFS_MP}"
+  fi
+  NEWUNIONRECORD="${NEWUNIONRECORD}${ONE_BASENAME} "
+  return 0
+@@ -546,36 +521,17 @@
+   /sbin/load_ext_file "$SAVE_FN" "$SAVE_MP" #reads $PFSCK
+   if [ -f /tmp/savefile_loop ] ; then
+     . /tmp/savefile_loop # $SAVEFILE_LOOP $SFFS
+-    if [ "$UNIONFS" = 'overlay' ]; then
+-      mkdir /pup_loop
+-      echo "mount -t $SFFS -o noatime $SAVEFILE_LOOP /pup_loop" #debug
+-      mount -t $SFFS -o noatime $SAVEFILE_LOOP /pup_loop
+-      if [ $? -ne 0 ]; then
+-        PUPSAVE=""
+-      else
+-        mkdir -p "/pup_loop/upper" "/pup_loop/work"
+-        ln -sv "/pup_loop/upper" "$SAVE_LAYER"
+-        ln -sv "/pup_loop/work" "$WORKDIR"
+-      fi
+-    else
+-      [ -d "$SAVE_LAYER" ] || mkdir $SAVE_LAYER
+-      echo "mount -t $SFFS -o noatime $SAVEFILE_LOOP $SAVE_LAYER" #debug
+-      mount -t $SFFS -o noatime $SAVEFILE_LOOP $SAVE_LAYER
+-      [ $? -ne 0 ] && PUPSAVE=""
+-    fi
++    [ -d "$SAVE_LAYER" ] || mkdir $SAVE_LAYER
++    echo "mount -t $SFFS -o noatime $SAVEFILE_LOOP $SAVE_LAYER" #debug
++    mount -t $SFFS -o noatime $SAVEFILE_LOOP $SAVE_LAYER
++    [ $? -ne 0 ] && PUPSAVE=""
+   else # load_ext_file failed
+     FLAG_NO_TIMEOUT=1
+     PUPSAVE=""
+   fi
+  elif [ -d "$SAVE_FN" ];then #savefolder
+   echo "--SAVEFOLDER-- $SAVE_FN" #debug
+-  if [ "$UNIONFS" = 'overlay' ]; then
+-   mkdir -p "$SAVE_FN/upper" "$SAVE_FN/work"
+-   ln -sv "$SAVE_FN/upper" "$SAVE_LAYER"
+-   ln -sv "$SAVE_FN/work" "$WORKDIR"
+-  else
+-   ln -sv "$SAVE_FN" "$SAVE_LAYER"
+-  fi
++  ln -sv "$SAVE_FN" "$SAVE_LAYER"
+  else
+   PUPSAVE=""
+  fi
+@@ -749,7 +705,7 @@
  
  search_func() {
   [ "$PDEBUG" -a "$LOOK_SAVE" ] && echo "3: filename=${PSUBDIR}/${DISTRO_FILE_PREFIX}save"
@@ -100,11 +201,11 @@
   echo "HAVE_PARTS='${HAVE_PARTS}'" #debug
   if [ "${1}" ];then
    echo "param='${1}'" #debug
-@@ -727,12 +719,15 @@
+@@ -776,12 +732,15 @@
      fi
     fi
     if [ "$LOOK_PUP" ];then
--    find_drv_file "$P_BP_FN" "$P_DEF_FN"
+-    find_drv_file "$P_BP_FN" "$P_DEF_FN" ""
 +    find_drv_file "$ONE_MP" "${PSUBDIR}/$ONE_DEF_FN"
      if [ "$ONE_FN" ];then
 -     PDRV="$ONE_PART,$ONE_FS,$ONE_FN"
@@ -120,7 +221,15 @@
       break;
      fi
     fi
-@@ -886,19 +881,15 @@
+@@ -898,6 +857,7 @@
+ else
+  WAITDEV=5
+ fi
++[ $punionfs ] && UNIONFS=$punionfs
+ 
+ #[ $pdebug ] && PDEBUG=$pdebug
+ PDEBUG=1
+@@ -935,19 +895,15 @@
    . /sbin/isoboot # optional, can remove all occurrences of "isoboot" from this script
  fi
  
@@ -138,10 +247,10 @@
  
 -[ "$PDEBUG" ] && echo "1: PDRV=$PDRV P_BP_ID=$P_BP_ID P_BP_FN=$P_BP_FN"
 -
- get_part_info
- grep -v '^sr' /tmp/ALLDRVS0 > /tmp/ATADRIVES0
- ATAOPTICALDRIVES="$(grep '^sr' /tmp/ALLDRVS0 | tr '\n' ' ')"
-@@ -920,7 +911,7 @@
+ #completely sortout info on the stack structure
+ #create appropriate stack only at the end, either aufs or overlayfs
+ RO_DIR_LIST=''			# ':' separated list of sfs MP's in stack order
+@@ -973,7 +929,7 @@
   wait_for_blkid 'iso9660' 'fs'
   if [ "$BLKID_PART" ];then
    if [ "$(echo $BLKID_PART | wc -w)" = "1" ];then
@@ -150,7 +259,7 @@
    fi
   fi
  fi
-@@ -939,7 +930,8 @@
+@@ -992,7 +948,8 @@
    else
      search_func
    fi
@@ -160,7 +269,15 @@
  fi
  if [ $STATUS -gt 0 ];then
   P_PRE_MSG="${L_PRE_MESSAGE}"
-@@ -985,7 +977,6 @@
+@@ -1020,7 +990,6 @@
+   LOADMSG="${ONE_DRV}drv"
+   process_one_sfs "$ONE_DRV" 'p'
+ done
+-
+ echo --------------------
+ 
+ #establish SAVEPART
+@@ -1038,7 +1007,6 @@
    fi
  fi
  #process SAVEMARK
@@ -168,7 +285,7 @@
  if [ "$P_PART" ];then
   BOOTDRV="$(echo -n "$P_PART" | grep -o -f /tmp/ALLDRVS0)" #110205 ex: sda1 becomes sda.
   if [ "$SAVEPART" = "" ];then #setup SAVEPART
-@@ -994,6 +985,7 @@
+@@ -1047,6 +1015,7 @@
    if [ "$PSAVEMARK" -a "$BOOTDRV" ];then
     ONE_PART="${BOOTDRV}${PSAVEMARK}" #note, PSAVEMARK could also be a kernel boot param. ex: 2
     if [ "$(echo $HAVE_PARTS | grep "$ONE_PART")" ];then #partition exists
@@ -176,7 +293,7 @@
      SAVEPART="$ONE_PART"; PSAVEPART="$ONE_PART"; SAVE_BP_DIR="${PSUBDIR}/"
      PSAVEMARK=''
     fi
-@@ -1032,7 +1024,6 @@
+@@ -1085,7 +1054,6 @@
  [ "$SAVEPART" ] || SAVEPART="$P_PART"
  
  #ensure that save partition is mounted
@@ -184,7 +301,117 @@
  #moved up here to ensure config files are available
  [ "$SAVEPART" ] && ensure_save_mounted
  
-@@ -1257,7 +1248,7 @@
+@@ -1113,9 +1081,6 @@
+  done
+ fi
+ 
+-#find PUPSAVE, sortout pupmode
+-PUPMODE=5
+-
+ #debug
+ echo --------------------
+ echo "SAVE_MP=${SAVE_MP}"
+@@ -1124,7 +1089,11 @@
+ mount
+ echo --------------------
+ 
+-PUPSAVE=""
++#find PUPSAVE, sortout pupmode
++PUPSAVE=''
++PUPMODE=5
++RW_DIR='/mnt/tmpfs/pup_rw'
++
+ if [ "${SAVE_MP}" != "" -a "$PRAMONLY" != "yes" ];then #have mounted save? partition
+  #check if save partition is linux
+  set_fs_linux "$SAVE_FS"
+@@ -1220,7 +1189,6 @@
+ fi
+ 
+ SAVE_LAYER=""
+-WORKDIR="/pup_work"
+ if [ "$PUPSAVE" ];then #refine pupmode
+  # refine pupmode
+  if [ $PUPMODE -eq 12 ];then
+@@ -1245,45 +1213,23 @@
+   [ $PUPMODE -eq 77 ] && copy_folders #to /pup_ro1 (part of the tmpfs)
+   [ $PUPMODE -eq 13 ] && setup_psave
+   if [ "$PUPSAVE" ] ; then
++    RO_DIR="$SAVE_LAYER"
+     #prepend ro1 - #SAVE_LAYER=/pup_ro1
+     rm -rf ${SAVE_LAYER}/tmp #in case last boot was pupmode=12
+-    #adjust stack
+-    if [ "$UNIONFS" = 'overlay' ]; then
+-     #pup_rw is bigger because files are copied, not moved to pup_ro1
+-     mount -o remount,size=75% /mnt/tmpfs
+-     remount_overlay "s~lowerdir=([^,]+)~lowerdir=${SAVE_LAYER}:\1~"
+-    else
+-     echo "mount -o remount,add:1:${SAVE_LAYER}=ro+wh /pup_new" #debug
+-     mount -o remount,add:1:${SAVE_LAYER}=ro+wh /pup_new #ro+wh = Readonly branch and it has/might have whiteouts on it
+-    fi
+-    if [ $? -eq 0 ];then
+       [ $PUPMODE -ne 77 ] && KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
+       [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
+-    else
+-      printf "${L_ADDING_SAVE_LAYER_FAILED}\n" "$SAVE_LAYER"
+-    fi
+   fi
+  ;;
+  12) #replace rw
+   setup_psave
+   if [ "$PUPSAVE" ] ; then
++    RW_DIR="$SAVE_FN"
+     #SAVE_LAYER=/pup_rw
+     #setup empty /tmp on tmpfs for in stack
+     rm -rf ${SAVE_LAYER}/tmp
+-    #adjust stack
+-    if [ "$UNIONFS" = 'overlay' ]; then
+-     remount_overlay -e "s~upperdir=[^,]+~upperdir=${SAVE_LAYER}~" -e "s~workdir=[^,]+~workdir=${WORKDIR}~"
+-    else
+-     echo "mount -o remount,prepend:${SAVE_LAYER}=rw,mod:/mnt/tmpfs/pup_rw=ro,del:/mnt/tmpfs/pup_rw /pup_new" #debug
+-     mount -o remount,prepend:${SAVE_LAYER}=rw,mod:/mnt/tmpfs/pup_rw=ro,del:/mnt/tmpfs/pup_rw /pup_new
+-    fi
+-    if [ $? -eq 0 ];then
+       rm -rf /mnt/tmpfs/pup_rw
+       KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
+       [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
+-    else
+-      printf "${L_ADDING_SAVE_LAYER_FAILED}\n" "$SAVE_LAYER"
+-    fi
+   fi
+  ;;
+  66) #extract to stack at new tmpfs
+@@ -1295,27 +1241,12 @@
+     rm -r -f "$PM66_DIR"
+     [ -d "$PM66_DIR" ] || mkdir $PM66_DIR
+     mount -t tmpfs tmpfs $PM66_DIR
+-    if [ "$UNIONFS" = 'overlay' ]; then
+-      mkdir $PM66_DIR/upper $PM66_DIR/work
+-      tar xf "$ARCHIVE_FN" -m -C $PM66_DIR/upper 2>/dev/null
+-      STATUS=$?
+-      if [ $STATUS -eq 0 ];then
+-        remount_overlay -e "s~upperdir=[^,]+~upperdir=${PM66_DIR}/upper~" -e "s~workdir=[^,]+~workdir=${PM66_DIR}/work~"
+-        STATUS=$?
+-      fi
+-    else
+-      tar xf "$ARCHIVE_FN" -m -C $PM66_DIR 2>/dev/null
+-      STATUS=$?
+-      if [ $STATUS -eq 0 ];then
+-        #replace rw branch with new populated tmpfs
+-        echo "mount -o remount,prepend:${PM66_DIR}=rw,mod:/mnt/tmpfs/pup_rw=ro,del:/mnt/tmpfs/pup_rw /pup_new" #debug
+-        mount -o remount,prepend:${PM66_DIR}=rw,mod:/mnt/tmpfs/pup_rw=ro,del:/mnt/tmpfs/pup_rw /pup_new
+-        STATUS=$?
+-      fi
+-    fi
++    tar xf "$ARCHIVE_FN" -m -C $PM66_DIR 2>/dev/null
++    STATUS=$?
+     if [ $STATUS -eq 0 ];then
+       SAVE_MP=''
+       rm -rf /mnt/tmpfs/pup_rw
++      RW_DIR="$PM66_DIR"
+     else
+       printf "${L_ADDING_SAVE_LAYER_FAILED}\n" "$PM66_DIR"
+     fi
+@@ -1390,7 +1321,7 @@
  
  echo -n $(($TOTAL_SIZEK_SFS_RAM - 5)) > /tmp/sfs_ram_sizek
  
@@ -193,7 +420,7 @@
  [ "$ATADRIVES" ] || ATADRIVES="$(cat /tmp/ATADRIVES0 | tr '\n' ' ')"
  
  mkdir -p /pup_new/etc/rc.d
-@@ -1265,7 +1256,7 @@
+@@ -1398,7 +1329,7 @@
  echo "PUPMODE=$PUPMODE"
  echo "PDEV1='$P_PART'"
  echo "DEV1FS='$DEV1FS'"
@@ -202,7 +429,7 @@
  echo "PUPSAVE='$PUPSAVE'"
  echo "PMEDIA='$PMEDIA'"
  echo '#ATADRIVES is all internal ide/pata/sata drives, excluding optical, excluding usb...'
-@@ -1279,12 +1270,6 @@
+@@ -1412,12 +1343,6 @@
  echo "#The partition that has the ${DISTRO_FILE_PREFIX}save file is mounted here..."
  echo "PUP_HOME='${SAVE_MP}'"
  echo '#(in /initrd) ...note, /mnt/home is a link to it.'
@@ -215,7 +442,7 @@
  echo '#Partition no. override on boot drive to which session is (or will be) saved...'
  echo "PSAVEMARK='$PSAVEMARK'"
  echo "PSAVEPART='$PSAVEPART'"
-@@ -1295,6 +1280,8 @@
+@@ -1428,6 +1353,8 @@
  echo "DOMIBS='no'"
  [ -f /sbin/set_plang ] && plang_pupstate #echo
  ) > /pup_new/etc/rc.d/PUPSTATE
@@ -224,3 +451,25 @@
  
  if [ "$PUPSAVE" ];then
   xBOOTCONFIG="$(grep -v '^PREVUNIONRECORD' /pup_new/etc/rc.d/BOOTCONFIG | sed -e 's/^LASTUNIONRECORD/PREVUNIONRECORD/')"
+@@ -1442,17 +1369,15 @@
+ 
+ echo "Moving mountpoints to /pup_new/initrd for after switch..." #debug
+ rm -r -f "/pup_new/initrd${SAVE_LAYER}"
+-OPT="move"
+-[ "$UNIONFS" = 'overlay' ] && OPT="bind"
+ for ONEMNT in $(mount | cut -f 3 -d ' ' | grep -v 'pup_new' | grep '^/pup_' | tr '\n' ' ');do
+  mkdir -p /pup_new/initrd${ONEMNT}
+- echo "mount -o $OPT $ONEMNT /pup_new/initrd${ONEMNT}" #debug
+- mount -o $OPT $ONEMNT /pup_new/initrd${ONEMNT}
++ echo "mount -o move $ONEMNT /pup_new/initrd${ONEMNT}" #debug
++ mount -o move $ONEMNT /pup_new/initrd${ONEMNT}
+ done
+ for ONEMNT in $(mount | cut -f 3 -d ' ' | grep '^/mnt/' | tr '\n' ' ');do
+  mkdir -p /pup_new/initrd${ONEMNT}
+- echo "mount -o $OPT $ONEMNT /pup_new/initrd${ONEMNT}" #debug
+- mount -o $OPT $ONEMNT /pup_new/initrd${ONEMNT}
++ echo "mount -o move $ONEMNT /pup_new/initrd${ONEMNT}" #debug
++ mount -o move $ONEMNT /pup_new/initrd${ONEMNT}
+ done
+ 
+ echo -------------------- # debug
