woofce changed

diff --git a/3update.diff b/3update.diff
--- a/3update.diff
+++ b/3update.diff
@@ -1,5 +1,15 @@
---- init.ins	2022-07-24 03:16:52.188097607 +1000
-+++ init+drv+overlay	2022-07-23 17:39:49.630004000 +1000
+--- init	2022-09-25 12:57:54.149022350 +1000
++++ init+overlay	2022-09-25 12:59:31.057028890 +1000
+@@ -28,8 +28,8 @@
+ L_UPGRADE_NO="Backing off, not using personal storage, booting in RAM only, PUPMODE=5..."
+ L_LOADING_FROM_CD="Loading folder %s from CD/DVD..." #printf
+ L_RAM_DISK_FULL="RAM disk full, copy failed at %s" #printf
+-L_ADDING_SAVE_LAYER_FAILED="adding %s to aufs stack failed." #printf
+ L_WAITING_FOR_DEV='Waiting %s seconds for slow storage devices.' #printf
++L_TAR_ARCHIVE_FAILED="Extracting tar archive %s failed." #printf
+ L_WAITING_FOR_PART='Waiting for partition [%s]' #printf
+ L_LOADING_KEYBOARD_LAYOUT="Loading '%s' keyboard layout..." #printf
+ L_COPY_MESSAGE="copying to ram"
 @@ -45,7 +45,7 @@
  L_SWITCH_ROOT="Performing a 'switch_root' to the %s filesystem..." #printf
  L_FOLDER_MARKED_BAD="Folder %s marked bad." #printf
@@ -9,6 +19,15 @@
  L_ADDING_MODULE="Adding module %s" #printf
  L_NO_DISTRO_SPECS="No DISTRO_SPECS file found, assuming that personal storage is empty."
  L_DEBUG_SAVE="To save debug info to a partition, type 'debugsave'"
+@@ -90,7 +90,7 @@
+ #Filesystem to be fsck
+ FSCKLIST="ext2|ext3|ext4|vfat|msdos|exfat"
+ 
+-# Layered file system to use
++# Default layered file system
+ UNIONFS='aufs'
+ 
+ # ?drv_...sfs files to load below puppy_...sfs
 @@ -182,9 +182,13 @@
    sleep 1
    echo -en "\\033[1;33m.\\033[0;39m" >/dev/console #yellow dot
@@ -25,7 +44,7 @@
    if [ "$PART" ];then
     check_status 0
    else
-@@ -254,10 +258,8 @@
+@@ -254,10 +258,10 @@
    if [ "$ONE_MP" != "$SAVE_MP" ];then
     #ensure SAVEPART is mounted on /mnt/dev_save
     [ -d "$SAVE_MP" ] || mkdir -p $SAVE_MP
@@ -35,47 +54,12 @@
 -   mount -o $OPT $ONE_MP $SAVE_MP
 +   echo "mount -o move $ONE_MP $SAVE_MP" #debug
 +   mount -o move $ONE_MP $SAVE_MP
++   #re-establish P_MP if PDRV was the moved partition MP
++   [ "$SAVEPART" = "$P_PART" ] && P_MP="$SAVE_MP"
    fi
    SAVE_FS="$ONE_FS"
   else
-@@ -423,29 +429,14 @@
- }
- 
- setup_onepupdrv() {
--# "$1" - sfs spec - ex: sdb2,ext4,/pup/mydrv-1.2.3.sfs
--# "$2" - suffix for "pup_" branch directory - ex: a
--# "$3" - prepend after rw layer indicator - ex: p
-+# "$1" - suffix for "pup_" branch directory - ex: a
-+# "$2" - prepend after rw layer indicator - ex: p  
-+#  use $SPEC_PART $SPEC_MP $SPEC_REL_FN
-  ONE_LAYER=""
-- ONE_PART="$(echo "${1}" | cut -f 1 -d ',')"
-- [ "$ONE_PART" ] || return 1
-- ONE_REL_FN="$(echo "${1}" | cut -f 3 -d ',')"
-- [ "$ONE_REL_FN" ] || return 1
-- ONE_SFX="${2}"
-- ONE_PREP="${3}"
-- if [ "$ONE_PART" = "rootfs" ];then #humongous initrd.
--  ONE_MP="" #actually it's '/'.
--  COPY2RAM='yes' #actually it is already in ram, but load_sfs_file code puts it in a tmpfs.
-- else
--  if [ "$ONE_PART" = "$P_PART" ];then
--   ONE_MP="$P_MP"
--  else
--   ONE_MP="$(mount | grep -m1 "/dev/$ONE_PART " | cut -f 3 -d ' ')"
--   [ "$ONE_MP" ] || return 2
--  fi
-- fi
-- ONE_FN="${ONE_MP}${ONE_REL_FN}"
-- ONE_BASENAME="$(basename $ONE_REL_FN)"
-+ ONE_SFX="${1}"
-+ ONE_PREP="${2}"
-+ ONE_FN="${SPEC_MP}${SPEC_REL_FN}"
-+ ONE_BASENAME="$(basename $SPEC_REL_FN)"
-  if ! [ -s "$ONE_FN" ] ; then
-    return 3 #sfs not Ok - empty file
-  fi
-@@ -458,6 +449,9 @@
+@@ -443,6 +447,9 @@
     COPY2RAM="no"
   fi
   #-
@@ -85,7 +69,7 @@
   if [ "$COPY2RAM" = "" ];then
    COPY2RAM="no"
    #if there's heaps of ram, copy puppy.sfs to a tmpfs...
-@@ -474,22 +468,22 @@
+@@ -459,57 +466,36 @@
    SIZEZK=$(du -k $ONE_FN | cut -f 1)
    TFREEK=$(df | grep -m1 ' /mnt/tmpfs' | tr -s ' ' | cut -f 4 -d ' ')
    if [ $TFREEK -gt $SIZEZK ];then
@@ -113,15 +97,20 @@
   fi
   SFS_MP="/pup_${ONE_SFX}"
   [ "$ONE_SFX" = "p" ] && SFS_MP="/pup_ro2"
-@@ -501,31 +495,12 @@
-  if ! [ "$ONE_LAYER" ] ; then
-    return 4 #sfs mount failed
-  fi
+  [ -d "$SFS_MP" ] || mkdir $SFS_MP
+  mount -r -t squashfs -o noatime $ONE_LOOP $SFS_MP > /dev/console 2>&1
+- STATUS=$? ; check_status $STATUS
+- [ $STATUS -eq 0 ] && ONE_LAYER="$SFS_MP=rr"
++ STATUS=$?; check_status $STATUS
++ [ $STATUS -eq 0 ] || return 4 #sfs mount failed
+  # ======= end of load_sfs_file()
+- if ! [ "$ONE_LAYER" ] ; then
+-   return 4 #sfs mount failed
+- fi
 - if [ -n "$punionfs" ]; then
 -  UNIONFS="$punionfs"
-- elif [ -f $SFS_MP/etc/rc.d/PUPSTATE ]; then
--  . $SFS_MP/etc/rc.d/PUPSTATE
--  [ -n "$PUNIONFS" ] && UNIONFS="$PUNIONFS"
+- elif [ "$UNIONFS" = 'aufs' ]; then
+-  grep -qm1 aufs /proc/filesystems || UNIONFS="overlay"
 - fi
 - if [ "$UNIONFS" = 'overlay' ]; then
 -  remount_overlay -e "s~lowerdir=([^,]+)~lowerdir=${SFS_MP}:\1~" -e "s~lowerdir=,~lowerdir=${SFS_MP},~"
@@ -150,7 +139,7 @@
   fi
   NEWUNIONRECORD="${NEWUNIONRECORD}${ONE_BASENAME} "
   return 0
-@@ -546,36 +521,17 @@
+@@ -530,22 +516,13 @@
    /sbin/load_ext_file "$SAVE_FN" "$SAVE_MP" #reads $PFSCK
    if [ -f /tmp/savefile_loop ] ; then
      . /tmp/savefile_loop # $SAVEFILE_LOOP $SFFS
@@ -165,19 +154,21 @@
 -        ln -sv "/pup_loop/upper" "$SAVE_LAYER"
 -        ln -sv "/pup_loop/work" "$WORKDIR"
 -      fi
--    else
++    [ -e /mnt/pup_loop ] || mkdir /mnt/pup_loop
++    echo "mount -t $SFFS -o noatime $SAVEFILE_LOOP /mnt/pup_loop" #debug
++    mount -t $SFFS -o noatime $SAVEFILE_LOOP /mnt/pup_loop
++    if [ $? -eq 0 ]; then
++      ln -sv '/mnt/pup_loop' "$SAVE_LAYER"
+     else
 -      [ -d "$SAVE_LAYER" ] || mkdir $SAVE_LAYER
 -      echo "mount -t $SFFS -o noatime $SAVEFILE_LOOP $SAVE_LAYER" #debug
 -      mount -t $SFFS -o noatime $SAVEFILE_LOOP $SAVE_LAYER
 -      [ $? -ne 0 ] && PUPSAVE=""
--    fi
-+    [ -d "$SAVE_LAYER" ] || mkdir $SAVE_LAYER
-+    echo "mount -t $SFFS -o noatime $SAVEFILE_LOOP $SAVE_LAYER" #debug
-+    mount -t $SFFS -o noatime $SAVEFILE_LOOP $SAVE_LAYER
-+    [ $? -ne 0 ] && PUPSAVE=""
++      PUPSAVE=""
+     fi
    else # load_ext_file failed
      FLAG_NO_TIMEOUT=1
-     PUPSAVE=""
+@@ -553,18 +530,18 @@
    fi
   elif [ -d "$SAVE_FN" ];then #savefolder
    echo "--SAVEFOLDER-- $SAVE_FN" #debug
@@ -192,7 +183,18 @@
   else
    PUPSAVE=""
   fi
-@@ -749,7 +705,7 @@
+  #[ "$PUPSAVE" ] && decrypt directory at SAVE_LAYER
+  if [ "$PUPSAVE" ];then
++  if [ "$UNIONFS" = 'overlay' ];then
++   SAVE_DIR="$(readlink "$SAVE_LAYER")/upper"
++   [ -e "$SAVE_DIR" ] || mkdir -p "$SAVE_DIR"
++   rm "$SAVE_LAYER"
++   ln -sv "$SAVE_DIR" "$SAVE_LAYER"
++  fi
+   SAVE_NAME="$(basename $SAVE_REL_FN)"
+   #- fix for empty pupsaves (missing /initrd/DISTRO_SPECS)
+   if [ ! -f "$SAVE_LAYER/initrd/DISTRO_SPECS" ] ; then
+@@ -733,7 +710,7 @@
  
  search_func() {
   [ "$PDEBUG" -a "$LOOK_SAVE" ] && echo "3: filename=${PSUBDIR}/${DISTRO_FILE_PREFIX}save"
@@ -201,7 +203,7 @@
   echo "HAVE_PARTS='${HAVE_PARTS}'" #debug
   if [ "${1}" ];then
    echo "param='${1}'" #debug
-@@ -776,12 +732,15 @@
+@@ -760,12 +737,15 @@
      fi
     fi
     if [ "$LOOK_PUP" ];then
@@ -221,71 +223,18 @@
       break;
      fi
     fi
-@@ -898,6 +857,7 @@
+@@ -882,6 +862,10 @@
  else
   WAITDEV=5
  fi
 +[ $punionfs ] && UNIONFS=$punionfs
++if [ "$UNIONFS" = 'aufs' ]; then
++  grep -qm1 aufs /proc/filesystems || UNIONFS="overlay"
++fi
  
  #[ $pdebug ] && PDEBUG=$pdebug
  PDEBUG=1
-@@ -935,19 +895,15 @@
-   . /sbin/isoboot # optional, can remove all occurrences of "isoboot" from this script
- fi
- 
--[ "$PDEBUG" ] && echo "0: PMEDIA=$PMEDIA PDRV=$PDRV PSUBDIR=$PSUBDIR pfix=$pfix"
-+[ "$PDEBUG" ] && echo "0: PMEDIA=$PMEDIA PDRV=$PDRV PSUBDIR=$PSUBDIR PSAVE=$PSAVE pfix=$pfix"
- 
- #setup wireless
- [ "$PWIRELESS" ] && echo -e "SSID=${PWIRELESS%:*}\nPSWD=${PWIRELESS#*:}" > /tmp/wireless.conf
- 
--get_part_info
--
- PUP_SAVES=""
- KEEPMOUNTED=""
- FSCKDPARTS=""
- 
--[ "$PDEBUG" ] && echo "1: PDRV=$PDRV P_BP_ID=$P_BP_ID P_BP_FN=$P_BP_FN"
--
- #completely sortout info on the stack structure
- #create appropriate stack only at the end, either aufs or overlayfs
- RO_DIR_LIST=''			# ':' separated list of sfs MP's in stack order
-@@ -973,7 +929,7 @@
-  wait_for_blkid 'iso9660' 'fs'
-  if [ "$BLKID_PART" ];then
-   if [ "$(echo $BLKID_PART | wc -w)" = "1" ];then
--   P_BP_ID="$BLKID_PART"
-+   PDRV="$BLKID_PART"
-   fi
-  fi
- fi
-@@ -992,7 +948,8 @@
-   else
-     search_func
-   fi
-- fi
-+  setup_onepupdrv 'p'
-+  STATUS=$?
- fi
- if [ $STATUS -gt 0 ];then
-  P_PRE_MSG="${L_PRE_MESSAGE}"
-@@ -1020,7 +990,6 @@
-   LOADMSG="${ONE_DRV}drv"
-   process_one_sfs "$ONE_DRV" 'p'
- done
--
- echo --------------------
- 
- #establish SAVEPART
-@@ -1038,7 +1007,6 @@
-   fi
- fi
- #process SAVEMARK
--decode_other_ids
- if [ "$P_PART" ];then
-  BOOTDRV="$(echo -n "$P_PART" | grep -o -f /tmp/ALLDRVS0)" #110205 ex: sda1 becomes sda.
-  if [ "$SAVEPART" = "" ];then #setup SAVEPART
-@@ -1047,6 +1015,7 @@
+@@ -1026,6 +1010,7 @@
    if [ "$PSAVEMARK" -a "$BOOTDRV" ];then
     ONE_PART="${BOOTDRV}${PSAVEMARK}" #note, PSAVEMARK could also be a kernel boot param. ex: 2
     if [ "$(echo $HAVE_PARTS | grep "$ONE_PART")" ];then #partition exists
@@ -293,7 +242,7 @@
      SAVEPART="$ONE_PART"; PSAVEPART="$ONE_PART"; SAVE_BP_DIR="${PSUBDIR}/"
      PSAVEMARK=''
     fi
-@@ -1085,7 +1054,6 @@
+@@ -1064,7 +1049,6 @@
  [ "$SAVEPART" ] || SAVEPART="$P_PART"
  
  #ensure that save partition is mounted
@@ -301,30 +250,7 @@
  #moved up here to ensure config files are available
  [ "$SAVEPART" ] && ensure_save_mounted
  
-@@ -1113,9 +1081,6 @@
-  done
- fi
- 
--#find PUPSAVE, sortout pupmode
--PUPMODE=5
--
- #debug
- echo --------------------
- echo "SAVE_MP=${SAVE_MP}"
-@@ -1124,7 +1089,11 @@
- mount
- echo --------------------
- 
--PUPSAVE=""
-+#find PUPSAVE, sortout pupmode
-+PUPSAVE=''
-+PUPMODE=5
-+RW_DIR='/mnt/tmpfs/pup_rw'
-+
- if [ "${SAVE_MP}" != "" -a "$PRAMONLY" != "yes" ];then #have mounted save? partition
-  #check if save partition is linux
-  set_fs_linux "$SAVE_FS"
-@@ -1220,7 +1189,6 @@
+@@ -1216,7 +1200,6 @@
  fi
  
  SAVE_LAYER=""
@@ -332,12 +258,13 @@
  if [ "$PUPSAVE" ];then #refine pupmode
   # refine pupmode
   if [ $PUPMODE -eq 12 ];then
-@@ -1245,45 +1213,23 @@
+@@ -1241,45 +1224,23 @@
    [ $PUPMODE -eq 77 ] && copy_folders #to /pup_ro1 (part of the tmpfs)
    [ $PUPMODE -eq 13 ] && setup_psave
    if [ "$PUPSAVE" ] ; then
+-    #prepend ro1 - #SAVE_LAYER=/pup_ro1
++    #SAVE_LAYER=/pup_ro1
 +    RO_DIR="$SAVE_LAYER"
-     #prepend ro1 - #SAVE_LAYER=/pup_ro1
      rm -rf ${SAVE_LAYER}/tmp #in case last boot was pupmode=12
 -    #adjust stack
 -    if [ "$UNIONFS" = 'overlay' ]; then
@@ -349,18 +276,20 @@
 -     mount -o remount,add:1:${SAVE_LAYER}=ro+wh /pup_new #ro+wh = Readonly branch and it has/might have whiteouts on it
 -    fi
 -    if [ $? -eq 0 ];then
-       [ $PUPMODE -ne 77 ] && KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
-       [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
+-      [ $PUPMODE -ne 77 ] && KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
+-      [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
 -    else
 -      printf "${L_ADDING_SAVE_LAYER_FAILED}\n" "$SAVE_LAYER"
 -    fi
++    [ $PUPMODE -ne 77 ] && KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
++    [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
    fi
   ;;
   12) #replace rw
    setup_psave
    if [ "$PUPSAVE" ] ; then
-+    RW_DIR="$SAVE_FN"
      #SAVE_LAYER=/pup_rw
++    RW_DIR="$(readlink $SAVE_LAYER)"
      #setup empty /tmp on tmpfs for in stack
      rm -rf ${SAVE_LAYER}/tmp
 -    #adjust stack
@@ -371,19 +300,26 @@
 -     mount -o remount,prepend:${SAVE_LAYER}=rw,mod:/mnt/tmpfs/pup_rw=ro,del:/mnt/tmpfs/pup_rw /pup_new
 -    fi
 -    if [ $? -eq 0 ];then
-       rm -rf /mnt/tmpfs/pup_rw
-       KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
-       [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
+-      rm -rf /mnt/tmpfs/pup_rw
+-      KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
+-      [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
 -    else
 -      printf "${L_ADDING_SAVE_LAYER_FAILED}\n" "$SAVE_LAYER"
 -    fi
++    rm -rf /mnt/tmpfs/pup_rw
++    KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
++    [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
    fi
   ;;
   66) #extract to stack at new tmpfs
-@@ -1295,27 +1241,12 @@
-     rm -r -f "$PM66_DIR"
-     [ -d "$PM66_DIR" ] || mkdir $PM66_DIR
-     mount -t tmpfs tmpfs $PM66_DIR
+@@ -1287,33 +1248,15 @@
+   if [ -s "$ARCHIVE_FN" ];then
+     echo -n "$(printf "${L_LOADING_SAVE_ARCHIVE}" "${PUPSAVE#*,*,}" "$SAVEPART")" > /dev/console
+     echo "--SAVEARCHIVE-- $ARCHIVE_FN" #debug
+-    PM66_DIR='/pup_rw'
+-    rm -r -f "$PM66_DIR"
+-    [ -d "$PM66_DIR" ] || mkdir $PM66_DIR
+-    mount -t tmpfs tmpfs $PM66_DIR
 -    if [ "$UNIONFS" = 'overlay' ]; then
 -      mkdir $PM66_DIR/upper $PM66_DIR/work
 -      tar xf "$ARCHIVE_FN" -m -C $PM66_DIR/upper 2>/dev/null
@@ -402,25 +338,21 @@
 -        STATUS=$?
 -      fi
 -    fi
-+    tar xf "$ARCHIVE_FN" -m -C $PM66_DIR 2>/dev/null
++    PM66_DIR="$RW_DIR"
++    [ -d "$PM66_DIR" ] || mkdir -p "$PM66_DIR"
++    tar xf "$ARCHIVE_FN" -m -C "$PM66_DIR" 2>/dev/null
 +    STATUS=$?
      if [ $STATUS -eq 0 ];then
        SAVE_MP=''
-       rm -rf /mnt/tmpfs/pup_rw
-+      RW_DIR="$PM66_DIR"
+-      rm -rf /mnt/tmpfs/pup_rw
++      ln -sv "$PM66_DIR" /pup_rw
      else
-       printf "${L_ADDING_SAVE_LAYER_FAILED}\n" "$PM66_DIR"
+-      printf "${L_ADDING_SAVE_LAYER_FAILED}\n" "$PM66_DIR"
++      printf "${L_TAR_ARCHIVE_FAILED}\n" "$ARCHIVE_FN"
      fi
-@@ -1390,7 +1321,7 @@
- 
- echo -n $(($TOTAL_SIZEK_SFS_RAM - 5)) > /tmp/sfs_ram_sizek
- 
--[ "$DEV1FS" ] || DEV1FS="$(echo "$PDRV" | cut -f 2 -d ',')"
-+[ "$DEV1FS" ] || DEV1FS="$(echo "$PUPSFS" | cut -f 2 -d ',')"
- [ "$ATADRIVES" ] || ATADRIVES="$(cat /tmp/ATADRIVES0 | tr '\n' ' ')"
- 
- mkdir -p /pup_new/etc/rc.d
-@@ -1398,7 +1329,7 @@
+     check_status $STATUS
+   fi
+@@ -1387,7 +1330,7 @@
  echo "PUPMODE=$PUPMODE"
  echo "PDEV1='$P_PART'"
  echo "DEV1FS='$DEV1FS'"
@@ -429,7 +361,7 @@
  echo "PUPSAVE='$PUPSAVE'"
  echo "PMEDIA='$PMEDIA'"
  echo '#ATADRIVES is all internal ide/pata/sata drives, excluding optical, excluding usb...'
-@@ -1412,12 +1343,6 @@
+@@ -1401,12 +1344,6 @@
  echo "#The partition that has the ${DISTRO_FILE_PREFIX}save file is mounted here..."
  echo "PUP_HOME='${SAVE_MP}'"
  echo '#(in /initrd) ...note, /mnt/home is a link to it.'
@@ -442,7 +374,7 @@
  echo '#Partition no. override on boot drive to which session is (or will be) saved...'
  echo "PSAVEMARK='$PSAVEMARK'"
  echo "PSAVEPART='$PSAVEPART'"
-@@ -1428,6 +1353,8 @@
+@@ -1417,6 +1354,8 @@
  echo "DOMIBS='no'"
  [ -f /sbin/set_plang ] && plang_pupstate #echo
  ) > /pup_new/etc/rc.d/PUPSTATE
@@ -451,7 +383,7 @@
  
  if [ "$PUPSAVE" ];then
   xBOOTCONFIG="$(grep -v '^PREVUNIONRECORD' /pup_new/etc/rc.d/BOOTCONFIG | sed -e 's/^LASTUNIONRECORD/PREVUNIONRECORD/')"
-@@ -1442,17 +1369,15 @@
+@@ -1431,17 +1370,15 @@
  
  echo "Moving mountpoints to /pup_new/initrd for after switch..." #debug
  rm -r -f "/pup_new/initrd${SAVE_LAYER}"
